#!/usr/bin/env bash

find ./src -iname *.h -o -iname *.c | xargs clang-format -style="{BasedOnStyle: llvm, IndentWidth: 4, AllowShortFunctionsOnASingleLine: None, KeepEmptyLinesAtTheStartOfBlocks: false, ColumnLimit: 0}" -i
